"""
claude.release-notes.py

A utility script to fetch and parse the Claude Platform Release Notes 
(https://docs.anthropic.com/en/release-notes/overview).
It extracts the release dates and associated updates, converting them 
into a clean Markdown list with absolute URLs.

Requires: beautifulsoup4, markdownify

Usage:
    python3 scripts/claude.release-notes.py [output_path]

If output_path is not provided, it defaults to .tmp/claude_release_notes.md
"""

import urllib.request
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import sys
import re

try:
    from bs4 import BeautifulSoup
    from markdownify import markdownify as md
except ImportError:
    print("Error: Required libraries not installed. Please run 'pip install beautifulsoup4 markdownify'")
    sys.exit(1)

def main():
    base_url = "https://docs.anthropic.com"
    url = f"{base_url}/en/release-notes/overview"
    output_path = sys.argv[1] if len(sys.argv) > 1 else ".tmp/claude_release_notes.md"
    
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    
    try:
        print(f"Fetching {url}...")
        with urllib.request.urlopen(req) as response:
            html = response.read().decode('utf-8')
            
        print("Preprocessing HTML...")
        soup = BeautifulSoup(html, "html.parser")
        
        markdown = "# Claude Platform Release Notes\n\nLatest updates to the Claude API, SDKs, and Console.\n\n"
        
        # In the NextJS DOM structure, dates are rendered in <h3> tags containing a <div class="group">
        for h3 in soup.find_all('h3'):
            date_div = h3.find('div', class_='group')
            if date_div:
                date_text = date_div.get_text(strip=True)
                
                # To avoid text like "Copy link to clipboard" merging with the date,
                # we specifically target the div that doesn't have classes (the text node wrapper)
                for div in date_div.find_all('div', recursive=False):
                    if not div.get('class'):
                        date_text = div.get_text(strip=True)
                
                markdown += f"## {date_text}\n\n"
                
                # The updates are stored in the immediate sibling <ul> tag
                ul = h3.find_next_sibling('ul')
                if ul:
                    # Convert internal relative links to absolute ones
                    for a in ul.find_all('a'):
                        href = a.get('href')
                        if href and href.startswith('/'):
                            a['href'] = f"{base_url}{href}"
                    
                    for li in ul.find_all('li'):
                        text = md(str(li), escape_asterisks=False, escape_underscores=False).strip()
                        # Clean up redundant bullets generated by markdownify
                        text = re.sub(r'^[\*\-]\s+', '', text)
                        markdown += f"- {text}\n"
                        
                markdown += "\n"
                
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(markdown.strip() + "\n")
            
        print(f"Successfully converted and stored in {output_path}")
        
    except Exception as e:
        print(f"Failed to fetch or convert the page: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
